# DEFAULT | FAST | NP | COREF | PARSE | CHUNK | TOKEN |

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: org.apache.ctakes.rest.entity

  global-config:
    db-config:
      id-type: auto

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/umls?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ps1909
    password: pass
    driver-class-name: com.mysql.jdbc.Driver

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: DefaultHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1